site_name: i3 environment
pages:
- Home: index.md
- Unfinished:
  - Unified user experience: unified-user-experience.md
  - Colours: colours.md
  - Basics: basics.md
  - Keyboard: keyboard.md
  - Default applications: default-applications.md
  - Inter process communication: ipc.md

theme: material
